# Generated by Django 5.0.4 on 2024-05-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_tblforwrite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblforwrite',
            name='wr_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tblforwrite',
            name='wr_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tblforwrite',
            name='wr_modified',
            field=models.DateTimeField(),
        ),
    ]
